# Name of your application. Used to uniquely configure containers.
# setup server via ansible https://github.com/stereosupersonic/ansible-pi
service: podi

# Name of the container image.
image: stereosupersonic/podi

# Deploy to these servers.
#
# netcup: podi (v2202511195490398192)

servers:
  web:
    - 37.120.190.122
  # job:
  #   hosts:
  #     - 192.168.0.1
  #   cmd: bin/jobs

# Enable SSL auto certification via Let's Encrypt and allow for multiple apps on a single web server.
# Remove this section when using multiple web servers and ensure you terminate SSL at your load balancer.
#
# Note: If using Cloudflare, set encryption mode in SSL/TLS setting to "Full" to enable CF-to-app encryption.
proxy:
  ssl: true
  host: www.wartenberger.de

# Credentials for your image host.
registry:
  # Specify the registry server, if you're not using Docker Hub
  # server: registry.digitalocean.com / ghcr.io / ...
  username: stereosupersonic

  # Always use an access token rather than real password when possible.
  password:
    - KAMAL_REGISTRY_PASSWORD

# Inject ENV variables into containers (secrets come from .kamal/secrets).
env:
  secret:
    - RAILS_MASTER_KEY
    - ROLLBAR_ENABLED
    - ROLLBAR_ACCESS_TOKEN
    - NEWRELIC_LICENSE_KEY
    - AWS_SECRET
    - AWS_ACCESS_KEY
    - CLOUDFRONT_URL
    - S3_ACCESS_KEY
    - S3_BUCKET_NAME
    - S3_REGION
    - S3_SECRET_KEY
    - CLOUDINARY_API_KEY
    - CLOUDINARY_API_SECRET
    - CLOUDINARY_CLOUD_NAME
    - GEOIP_ACCOUNT
    - GEOIP_LICENSE_KEY


  clear:
    DATABASE_HOST: podi-postgres
    DEFAULT_URL_HOST: www.wartenberger.de
    # Run the Solid Queue Supervisor inside the web server's Puma process to do jobs.
    # When you start using multiple servers, you should split out job processing to a dedicated machine.
    SOLID_QUEUE_IN_PUMA: true
    RAILS_LOG_LEVEL: debug
    # Set number of processes dedicated to Solid Queue (default: 1)
    # JOB_CONCURRENCY: 3

    # Set number of cores available to the application on each server (default: 1).
    # WEB_CONCURRENCY: 2

    # Match this to any external database server to configure Active Record correctly
    # Use chickenhouse-db for a db accessory server on same machine via local kamal docker network.
    # DB_HOST: 192.168.0.2

    # Log everything from Rails
    # RAILS_LOG_LEVEL: debug

# Aliases are triggered with "bin/kamal <alias>". You can overwrite arguments on invocation:
# "bin/kamal logs -r job" will tail logs from the first server in the job section.
aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"


# Use a persistent storage volume for sqlite database files and local Active Storage files.
# Recommended to change this to a mounted volume path that is backed up off server.
volumes:
  - "podi_storage:/rails/storage"


# Bridge fingerprinted assets, like JS and CSS, between versions to avoid
# hitting 404 on in-flight requests. Combines all files from new and old
# version inside the asset_path.
# asset_path: /app/public/assets

# Configure the image builder.
builder:
  arch: amd64

  # # Build image via remote server (useful for faster amd64 builds on arm64 computers)
  # remote: ssh://docker@docker-builder-server
  #
  # # Pass arguments and secrets to the Docker build process
  # args:
  #   RUBY_VERSION: 3.2.5
  # secrets:
  #   - GITHUB_TOKEN
  #   - RAILS_MASTER_KEY

# Use a different ssh user than root
# https://kamal-deploy.org/docs/configuration/ssh/
ssh:
  user: stereosonic

accessories:
  postgres:
    image: postgres:17
    port: 127.0.0.1:5432:5432
    host: 37.120.190.122
    env:
      clear:
        POSTGRES_USER: postgres
        POSTGRES_DB: podi_production
      secret:
        - POSTGRES_PASSWORD
    directories:
      - data:/var/lib/postgresql/data

  postgres_backup:
    image: kartoza/pg-backup:17-3.5
    host:  37.120.190.122
    env:
      clear:
        POSTGRES_USER: postgres
        POSTGRES_HOST: podi-postgres
        DBLIST: podi_production # Only back up the primary DB
        POSTGRES_PORT: 5432
        REMOVE_BEFORE: "30"
        ARCHIVE_FILENAME: $(date +%Y-%m-%d_%H:%M:%S) # 2025-10-04_10:43:01.podi_production.dmp
        CRON_SCHEDULE: "0 2 * * *"  # Daily at 2 AM
      secret:
        - POSTGRES_PASS
    directories:
      - /home/stereosonic/backups:/backups
